import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import { ClerkProvider,SignedIn,SignIn,SignedOut } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-[#0f172a] via-[#1e293b] to-[#0f172a] text-white min-h-screen`}
  >
    <ClerkProvider>
      <SignedOut>
        <div className="min-h-screen flex items-center justify-center p-6">
          <div className="w-full max-w-sm bg-white/10 backdrop-blur-md rounded-2xl shadow-lg p-8 ring-1 ring-white/10">
            <h2 className="text-2xl font-semibold text-center mb-6">Welcome Back</h2>
            <SignIn routing="hash" />
          </div>
        </div>
      </SignedOut>
      <SignedIn>
        {children}
      </SignedIn>
    </ClerkProvider>
  </body>
</html>

  );
}
